name: architecture_template
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kartal: ^4.1.0
  vexana: ^5.0.2
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  envied: ^1.0.0
  easy_localization: ^3.0.7

#dependency_overrides:
#  cupertino_icons: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/app_icon.png"
flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter:
  uses-material-design: true

widgets:
  path: module/widgets

  assets:
    - assets/translations
